# Generated by Django 2.1 on 2018-08-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('inputdate', models.DateField()),
                ('definition', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=200)),
            ],
        ),
    ]
